### ISSUE TITLE
Un gatito llora, cada vez que...

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-GemmV#1]
A indentar ese código!

![](https://media.giphy.com/media/TZBED1pP5m8N2/giphy.gif)

**Comment by GemmV** [comment]
indentado

**Comment by nasivuela** [comment]
No olvides hacer commit y push de tus cambios ;)

**Comment by GemmV** [comment]
hecho, voy cerrando issues :)
