### ISSUE TITLE
Centrat título principal

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-GemmV#10]
Parece que el título le ha cogido cariño al menú. Vamos a ponerlo en su sitio centrandolo verticalmente!

- Hay que hacer que el body, o una etiqueta madre de header y main ocupe todo el alto (vh mola ;)
- Como ya le has puesto flex a esa etiqueta madre (body), hay que hacer que main (item flex) ocupe todo el alto libre que queda.
- Hay que centrar el título verticalmente, a darle caña a flex o a position absolute + transform :)

**Comment by GemmV** [comment]
me he liado un poco pero al final parece que ha quedado alineado todo.
