### ISSUE TITLE
Contenido de <title>

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-GemmV#2]
Ojo con el con el texto `La evaluasió`. A veces el contenido campechano mola, por ejemplo si estoy haciendo una web donde en general escribo los textos igual que se pronuncian en Andaluz, chachi.

Pero en este caso, la tónica de la web es otra. Vamos a arreglar ese `<title>` poniendo un texto más acorde al contenido.

**Comment by GemmV** [comment]
cambiado
