### ISSUE TITLE
Sustituir selectores de etiqueta por clases

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-GemmV#8]
En general intentamos poner selectores de clase `.logo_adalab {}`, ya que los de etiqueta `img { }` nos pueden dar dolores de cabeza en el futuro. 

Toda regla tiene sus excepciones, por ejempo para `body` si que usamos el selector de etiqueta, ya que solo hay uno en toda la página (buen trabajo ahí!)

¿Te animas a arreglar el resto?

**Comment by GemmV** [comment]
seh :)
